### ISSUE TITLE
Dockerfiles for Python 3.12 do not successfully build

### ISSUE THREAD

**Issue by TaperChipmunk32** [sillsdev/machine.py#135]
In the changes I made in this [PR](https://github.com/sillsdev/machine.py/pull/131), the dockerfile and dockerfile.cpu_only no longer build successfully after updating to Python 3.12.

It seems to be related to this [issue](https://github.com/python-poetry/poetry-plugin-export/issues/239) in poetry and can be fixed by adding urllib3 = "<2" to pyproject.toml

**Comment by johnml1135** [comment]
It's something wierder.  I can take a look at it @TaperChipmunk32  is you would like.

**Comment by TaperChipmunk32** [comment]
> It's something wierder.  I can take a look at it @TaperChipmunk32  is you would like.

Go for it. I couldn't quite figure it out today.

**Comment by johnml1135** [comment]
You will also need to make sure that you update all of your NVIDIA drivers to support CUDA 2.6.
You will also need to make sure that you update your clearml.conf file to have:
```
pip_version: ["<20.2 ; python_version < '3.10'", "<22.3 ; python_version >= '3.10' and python_version <= '3.11'", ">=23,<24.3 ; python_version >= '3.12'"]
```

**Comment by TaperChipmunk32** [comment]
> You will also need to make sure that you update all of your NVIDIA drivers to support CUDA 2.6. You will also need to make sure that you update your clearml.conf file to have:
> 
> ```
> pip_version: ["<20.2 ; python_version < '3.10'", "<22.3 ; python_version >= '3.10' and python_version <= '3.11'", ">=23,<24.3 ; python_version >= '3.12'"]
> ```

Where in clearml.conf is this needed, and can you add it to your PR with the other docker changes?

**Comment by johnml1135** [comment]
It is needed on the servers themselves (cheetah, aqua, etc.).  If they are using the most recent clearML agent, it should be fine.
