### ISSUE TITLE
Nonexistent status "stopping" in clearml_check_canceled()

### ISSUE THREAD

**Issue by mshannon-sil** [sillsdev/machine.py#26]
@johnml1135 @ddaspit In `machine/jobs/build_nmt_engine.py/run()/clearml_check_canceled()`, there is the following line: `if task.get_status() in {"stopped", "stopping"}:`. However, according to the [clearml task documentation](https://clear.ml/docs/latest/docs/references/sdk/task/#get_status), the only values for `TaskStatusEnum` are `[“created”, “in_progress”, “stopped”, “closed”, “failed”, “completed”, “queued”, “published”, “publishing”, “unknown”]`. There is no `stopping` status listed here. Should I go ahead and remove the check for the `stopping` status?

**Comment by johnml1135** [comment]
@ddaspit - I will defer to you.

**Comment by ddaspit** [comment]
I'm sure there was a reason why I checked for `stopping`, I just can't remember why. Maybe I encountered it in my testing. The only thing I can find is that the `status_message` gets set to `stopping` when task cancellation is first triggered.  Here we are checking `get_status()` and not the `status_message`, so it shouldn't ever get set to `stopping`.  If we remove it, we need to make sure that build cancellation still works. There are two ways that you can cancel a NMT build: from the Serval API and from the ClearML UI.
