### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.py#52]
The build doesn't seem to exist anymore - but here is the error log.
```
\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: SIL.Machine.AspNetCore.Services.ClearMLMonitorService[0]
      Build faulted (65419fb23627520aa5115888). Error: OutOfMemoryError : CUDA out of memory. 
      Tried to allocate 16.00 MiB (GPU 0; 23.68 GiB total capacity; 22.84 GiB already allocated; 47.50 MiB free; 23.24 GiB reserved in total by PyTorch) 
      If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  
      See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Should we use `PYTORCH_CUDA_ALLOC_CONF`?  Or, should we just use a smaller batch size when on a 3090 rather than the A100?  If so, let's have a recommendation to give out so that SF, etc. can reliably run jobs.

**Comment by johnml1135** [comment]
https://stackoverflow.com/questions/73747731/runtimeerror-cuda-out-of-memory-how-setting-max-split-size-mb

Alternatively, we may be able to catch out-of-memory errors and just `torch.cuda.empty_cache() ` - which should clear up the memory.  It's "expensive", but should be acceptable rather than bombing the entire pretranslation job.  I don't know the best implementation for this, possibly this pseudocode:

```
def pretranslate_all():
    for batch in pretranslations:
        try:
            pretranslate()
        except OutOfMemoryError as e:
            # See if clearing the cache helps
            torch.cuda.empty_cache() 
            pretranslate()

while(config["batch_size"] > 8):
    try:
        pretranslate_all()
        break
    except OutOfMemoryError as e:
        # let's reduce the batch size and try to pretranslate again 
        torch.cuda.empty_cache() 
        config["batch_size"] = config["batch_size"] // 2
```

After being able to successfully train the model, we should not be failing the job from OOM errors during pretranslate.  Through releasing cached memory and incrementally reducing the batch size, we should be able to avoid these errors.

**Comment by mshannon-sil** [comment]
In my experience I've usually needed to reduce the batch size when running jobs on the 3090, since it would fail during the training stage for me. However, I think the idea of clearing the cache and reducing the batch size automatically when encountering memory issues is a good one.

**Comment by ddaspit** [comment]
I believe we should investigate setting the batch size for inferencing to 1. This would remove the chance for OOM errors. Since we are aiming to support any language, we don't have a good handle on how variable verse lengths will be. If verse lengths are not regular, batching can have a negative impact on inferencing speed. Here are guidelines for batching from the [Huggingface transformers documentation](https://huggingface.co/docs/transformers/v4.34.1/main_classes/pipelines):

> For users, a rule of thumb is:
> - Measure performance on your load, with your hardware. Measure, measure, and keep measuring. Real numbers are the only way to go.
> - If you are latency constrained (live product doing inference), don’t batch
> - If you are using CPU, don’t batch.
> - If you are using throughput (you want to run your model on a bunch of static data), on GPU, then:
>     - If you have no clue about the size of the sequence_length (“natural” data), by default don’t batch, measure and try tentatively to add it, add OOM checks to recover when it will fail (and it will at some point if you don’t control the sequence_length.)
>     - If your sequence_length is super regular, then batching is more likely to be VERY interesting, measure and push it until you get OOMs.
>     - The larger the GPU the more likely batching is going to be more interesting
> - As soon as you enable batching, make sure you can handle OOMs nicely.

**Comment by johnml1135** [comment]
Biggest thing from the advice `As soon as you enable batching, make sure you can handle OOMs nicely.`  I will be ok with any solution that stops the OOMs.

**Comment by ddaspit** [comment]
Another relevant quote for our case is

> If you have no clue about the size of the sequence_length (“natural” data), by default don’t batch

**Comment by johnml1135** [comment]
More errors:
```
2023-11-02 12:39:57
ClearML Monitor: Could not detect iteration reporting, falling back to iterations as seconds-from-start
2023-11-02 12:41:27
Your input_length: 200 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-02 12:48:17
Your input_length: 188 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-02 12:54:27
Your input_length: 297 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-02 12:57:46
/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
2023-11-02 12:59:04
Your input_length: 218 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-02 13:06:05
Your input_length: 233 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-02 13:07:13
Your input_length: 596 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
rror: OutOfMemoryError : CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 39.39 GiB total capacity; 35.84 GiB already allocated; 13.94 MiB free; 38.88 GiB reserved in total by PyTorch)
```

@ddaspit - did we remove truncation?  It looks like a nearly 600 token segment caused it to bomb.  This may still be there even if we don't batch.  Someone could put in a 2000 token segment and still cause the issue.

**Comment by ddaspit** [comment]
Truncation hasn't been removed.

**Comment by johnml1135** [comment]
If that is so, why did the A100 get a OOM?

**Comment by johnml1135** [comment]
![image](https://github.com/sillsdev/machine.py/assets/13733556/c724350d-fe6f-4881-8e2a-0d7c6ef14483)
![image](https://github.com/sillsdev/machine.py/assets/13733556/9b34583e-33d9-4f44-949c-df42788d4712)

it appears that as the warnings about long segments get larger, more GPU memory is used.  If it is truncating, why would that be an issue?

**Comment by johnml1135** [comment]
It looks like the truncation strategy would be passed down - but has it been verified?

**Comment by ddaspit** [comment]
Yes, I verified it.

**Comment by ddaspit** [comment]
We are already running very close to the memory limit. If a batch contains a lot of 200 length verses, then it could push the memory usage over the limit. Dropping the batch size down to 1 should fix this issue.

**Comment by johnml1135** [comment]
I am reducing the batch size to 1 and then just waiting for the issue to happen again (if it will).

**Comment by johnml1135** [comment]
Timing for different batch sizes:
> For translating GEN, EXO, RUT, EST, and JON from Hindi to Maithili:
> The batch_size: 16 version finished in 14:50 (min:sec).
> The batch_size: 1 version finished in 53:49.
> Configs here if you're interested: S:\MT\experiments\FT-India\

**Comment by johnml1135** [comment]
Based upon it taking nearly 4 times as long without batching, let's batch, catch any OOM's and then reduce the batch size by half until we get to 1.

**Comment by johnml1135** [comment]
This has been resolved by auto-stepping down the batch size.
