### ISSUE TITLE
Torch compile for faster inferencing?

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.py#72]
"Depending on the model and the GPU, torch.compile() yields up to 30% speed-up during inference. To use torch.compile(), simply install any version of torch above 2.0."

```
model = AutoModelForImageClassification.from_pretrained(MODEL_ID).to("cuda")
+ model = torch.compile(model)
```

Can we do this?  What is the drawback?

**Comment by johnml1135** [comment]
@isaac091 - can you put in any findings here - why it may or may not work?

**Comment by isaac091** [comment]
Sure. I haven't tried it on just inferencing yet, but I will run those tests.

**Comment by isaac091** [comment]
Results documented in https://github.com/sillsdev/silnlp/pull/308
