### ISSUE TITLE
Restrict build options to only update model hyperparameters

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/machine.py#86]
The way that the build options is currently implemented allows a user to override any config parameter, including `data_dir` and `model_type`. We should restrict what parameters can be overridden. The build options should be merged with the model settings, i.e. the `huggingface` settings object.

**Comment by johnml1135** [comment]
So, we should restrict it to:
* model_type
* max_steps
* batch_size
* huggingface

**Comment by ddaspit** [comment]
I think we should restrict it to everything under `huggingface`.

**Comment by ddaspit** [comment]
Basically, the build options are merged into the `huggingface` section instead of the root-level.

**Comment by johnml1135** [comment]
Would we then rename `huggingface` to `build_params` or similar?  Or would we have a completely different implementation if it was openNMT or some other framework?  `build_params: backend: huggingface`?

Reference: https://github.com/sillsdev/machine.py/blob/main/machine/jobs/settings.yaml

**Comment by ddaspit** [comment]
There isn't any need to rename `huggingface`. We should be able to merge the build options directly into the `huggingface` object directly.

**Comment by johnml1135** [comment]
So @ddaspit , just to clarify:
* Put model_type, max_steps and batch_size under Huggingface in the settings file (and fix machine.py to make it work)
* Tell the users that now to change max_steps, they will have to do {` huggingface: { max_steps: ### } }`.
* Update Serval and wiki documentation to reflect the changes
* When taking in the options from ClearML, machine.py should filter on huggingface and not allow anything else through

Is that correct?
