### ISSUE TITLE
Failing test for corpora/test_parallel_text_corpus.py: test_to_hf_dataset()

### ISSUE THREAD

**Issue by sboisen** [sillsdev/machine.py#9]
Passing this along in case it's helpful. 

When i do `import datasets.iterable_dataset` interactively, there is an `IterableDataset` class, but nothing for `iterable_dataset`. 

---

poetry run pytest tests/corpora                                                                                                                                                       [10/02/23 | 11:26:01]
============================================================================================== test session starts ==============================================================================================
platform darwin -- Python 3.10.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/sboisen/git/sillsdev/machine.py, configfile: pyproject.toml
plugins: mockito-0.0.4, typeguard-2.13.3
collected 50 items

tests/corpora/test_dbl_bundle_text_corpus.py ..                                                                                                                                                           [  4%]
tests/corpora/test_parallel_text_corpus.py ........................F.                                                                                                                                     [ 56%]
tests/corpora/test_paratext_backup_text_corpus.py ..                                                                                                                                                      [ 60%]
tests/corpora/test_scripture_text_corpus.py .                                                                                                                                                             [ 62%]
tests/corpora/test_text_file_text.py ...                                                                                                                                                                  [ 68%]
tests/corpora/test_text_file_text_corpus.py .....                                                                                                                                                         [ 78%]
tests/corpora/test_usfm_file_text.py ....                                                                                                                                                                 [ 86%]
tests/corpora/test_usfm_file_text_corpus.py ..                                                                                                                                                            [ 90%]
tests/corpora/test_usfm_tokenizer.py ..                                                                                                                                                                   [ 94%]
tests/corpora/test_usx_zip_text.py ...                                                                                                                                                                    [100%]

=================================================================================================== FAILURES ====================================================================================================
______________________________________________________________________________________________ test_to_hf_dataset _______________________________________________________________________________________________

self = <machine.corpora.standard_parallel_text_corpus.StandardParallelTextCorpus object at 0x111a9f8b0>, source_lang = 'src', target_lang = 'trg', text_id_column = 'text', ref_column = 'ref'
translation_column = 'translation', alignment_column = 'alignment', info = None, split = None, format_type = None

    def to_hf_dataset(
        self,
        source_lang: str,
        target_lang: str,
        text_id_column: Optional[str] = "text",
        ref_column: Optional[str] = "ref",
        translation_column: str = "translation",
        alignment_column: Optional[str] = "alignment",
        info: Optional[DatasetInfo] = None,
        split: Optional[NamedSplit] = None,
        format_type: Optional[str] = None,
    ) -> IterableDataset:
        try:
            from datasets.features.features import Features, FeatureType, Sequence, Value
            from datasets.features.translation import Translation
            from datasets.info import DatasetInfo
>           from datasets.iterable_dataset import iterable_dataset
E           ImportError: cannot import name 'iterable_dataset' from 'datasets.iterable_dataset' (/Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/datasets/iterable_dataset.py)

machine/corpora/parallel_text_corpus.py:346: ImportError

During handling of the above exception, another exception occurred:

    def test_to_hf_dataset() -> None:
        source_corpus = DictionaryTextCorpus(
            MemoryText(
                "text1",
                [
                    text_row("text1", 1, "source segment 1 .", TextRowFlags.NONE),
                    text_row("text1", 2, "source segment 2 ."),
                    text_row("text1", 3, "source segment 3 ."),
                ],
            )
        )
        target_corpus = DictionaryTextCorpus(
            MemoryText(
                "text1",
                [
                    text_row("text1", 1, "target segment 1 ."),
                    text_row("text1", 2),
                    text_row("text1", 3, "target segment 3 .", TextRowFlags.NONE),
                ],
            )
        )
        alignment_corpus = DictionaryAlignmentCorpus(
            MemoryAlignmentCollection(
                "text1",
                [
                    alignment_row("text1", 1, AlignedWordPair(0, 0)),
                    alignment_row("text1", 2),
                    alignment_row("text1", 3, AlignedWordPair(2, 2)),
                ],
            )
        )

        parallel_corpus = StandardParallelTextCorpus(source_corpus, target_corpus, alignment_corpus)
>       ds = parallel_corpus.to_hf_dataset("src", "trg")

tests/corpora/test_parallel_text_corpus.py:1097:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <machine.corpora.standard_parallel_text_corpus.StandardParallelTextCorpus object at 0x111a9f8b0>, source_lang = 'src', target_lang = 'trg', text_id_column = 'text', ref_column = 'ref'
translation_column = 'translation', alignment_column = 'alignment', info = None, split = None, format_type = None

    def to_hf_dataset(
        self,
        source_lang: str,
        target_lang: str,
        text_id_column: Optional[str] = "text",
        ref_column: Optional[str] = "ref",
        translation_column: str = "translation",
        alignment_column: Optional[str] = "alignment",
        info: Optional[DatasetInfo] = None,
        split: Optional[NamedSplit] = None,
        format_type: Optional[str] = None,
    ) -> IterableDataset:
        try:
            from datasets.features.features import Features, FeatureType, Sequence, Value
            from datasets.features.translation import Translation
            from datasets.info import DatasetInfo
            from datasets.iterable_dataset import iterable_dataset
        except ImportError:
>           raise RuntimeError("datasets is not installed.")
E           RuntimeError: datasets is not installed.

machine/corpora/parallel_text_corpus.py:348: RuntimeError
============================================================================================ short test summary info ============================================================================================
FAILED tests/corpora/test_parallel_text_corpus.py::test_to_hf_dataset - RuntimeError: datasets is not installed.
========================================================================================= 1 failed, 49 passed in 3.35s ==========================================================================================

**Comment by ddaspit** [comment]
This error occurs with newer versions of the HF `datasets` library. It should be fixed now. Thanks for reporting the issue.
